### ISSUE TITLE
D3Cold in hybrid graphics mode (Wayland)

### ISSUE THREAD

**Issue by avra-m3** [linux-surface/surface-hotplug#6]
You can completely shut off the gpu when not in use by preventing Wayland from knowing nvidia exists (you need to remove/rename `/usr/share/glvnd/egl_vendor.d/10_nvidia.json`)  and unloading the nvidia drivers, we should incorporate this into the Runtime power mangement docs.

`sudo mv /usr/share/glvnd/egl_vendor.d/10_nvidia.json /usr/share/glvnd/egl_vendor.d/10_nvidia.json.backup`

Unsure if X-Server has something similarly usable.

This is also something we may be able to incorporate into the detach process eventually.

**Comment by avra-m3** [comment]
Edited page feel free to spruce it up

**Comment by qzed** [comment]
Thanks!

**Comment by spfanning** [comment]
I don't think moving the file is ideal, I have the following environment variables set to achieve the same thing (some may not be necessary):
```
__EGL_VENDOR_LIBRARY_FILENAMES="/usr/share/glvnd/egl_vendor.d/50_mesa.json"
VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json:/usr/share/vulkan/icd.d/intel_icd.i686.json
DXVK_FILTER_DEVICE_NAME="Intel"
VKD3D_FILTER_DEVICE_NAME="Intel"
__GLX_VENDOR_LIBRARY_NAME="mesa"
VDPAU_DRIVER=va_gl
```

To run a program on the nvidia gpu you just set the variables to the nvidia version. The `prime-run` wrapper does this.

**Comment by qzed** [comment]
Oh neat. I agree that this is probably a better idea than changing system files. Would you mind adding that to the wiki?

**Comment by spfanning** [comment]
Done.

**Comment by qzed** [comment]
Thanks!

**Comment by SnenxyTengoku** [comment]
bumping this thread that these environment variables don't work anymore as they should. using them breaks vulkan for the dgpu entirely (`VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.json` means *only* Intel loads vulkan, using `__EGL_VENDOR_LIBRARY_FILENAMES="/usr/share/glvnd/egl_vendor.d/50_mesa.json"` means nvidia *doesn't* load its required vulkan modules) that it'd either be better to just blacklist the nvidia modules or deal with not detaching the keyboard ever (or do, but at the risk that an application might be using it and then explode upon detachment). neither `prime-run` or `switcherooctl` fixes this as it supposedly should.

now, throwing `DXVK_FILTER_DEVICE_NAME="Intel"` and `VKD3D_FILTER_DEVICE_NAME="Intel"` into the mix *does* allow the dgpu to enter `D3Cold`, but again, vulkan just won't work with the dgpu, which leads to pretty much all reasoning for why one wants to use it off the table (because OpenGL *does* work, but Vulkan performs Better™)
